# Generated by Django 4.2.23 on 2025-11-25 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_service"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "buyer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buyer_chats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "seller"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seller_chats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_chats",
                        to="accounts.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Chat",
                "verbose_name_plural": "Service Chats",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ServiceChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("message", models.TextField(help_text="Message content")),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="accounts.servicechat",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_service_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Chat Message",
                "verbose_name_plural": "Service Chat Messages",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["chat", "created_at"], name="accounts_se_chat_id_199aed_idx"
                    ),
                    models.Index(fields=["chat", "is_read"], name="accounts_se_chat_id_748ee3_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="servicechat",
            index=models.Index(
                fields=["buyer", "-updated_at"], name="accounts_se_buyer_i_d41e17_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicechat",
            index=models.Index(
                fields=["seller", "-updated_at"], name="accounts_se_seller__3891d2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="servicechat",
            unique_together={("buyer", "seller", "service")},
        ),
    ]
