# Generated by Django 4.2.23 on 2025-11-25 23:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_servicechat_servicechatmessage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="account_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Payment"),
                    ("active", "Active"),
                    ("suspended", "Suspended"),
                ],
                db_index=True,
                default="pending",
                help_text="Account activation status",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="registration_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Amount paid for registration",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="registration_paid",
            field=models.BooleanField(
                default=False, help_text="Whether registration fee has been paid"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="registration_paid_at",
            field=models.DateTimeField(
                blank=True, help_text="When registration payment was completed", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="stripe_customer_id",
            field=models.CharField(
                blank=True, help_text="Stripe customer ID", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="stripe_payment_intent_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe payment intent ID for registration",
                max_length=255,
                null=True,
            ),
        ),
    ]
