# Generated by Django 4.2.23 on 2025-11-27 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_user_account_status_user_registration_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="buyer_access_paid",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether buyer dashboard access has been paid",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="buyer_payment_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Amount paid for buyer access",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="buyer_payment_date",
            field=models.DateTimeField(
                blank=True, help_text="When buyer access payment was completed", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="buyer_stripe_payment_intent_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe payment intent ID for buyer access",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="seller_access_paid",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether seller dashboard access has been paid",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="seller_payment_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Amount paid for seller access",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="seller_payment_date",
            field=models.DateTimeField(
                blank=True, help_text="When seller access payment was completed", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="seller_stripe_payment_intent_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe payment intent ID for seller access",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="registration_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="DEPRECATED: Amount paid for registration",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="registration_paid",
            field=models.BooleanField(
                default=False, help_text="DEPRECATED: Whether registration fee has been paid"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="registration_paid_at",
            field=models.DateTimeField(
                blank=True,
                help_text="DEPRECATED: When registration payment was completed",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="stripe_payment_intent_id",
            field=models.CharField(
                blank=True,
                help_text="DEPRECATED: Stripe payment intent ID for registration",
                max_length=255,
                null=True,
            ),
        ),
    ]
