# Generated by Django 4.2.23 on 2025-11-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_user_buyer_access_paid_user_buyer_payment_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="stripe_account_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Seller's Stripe Connect Account ID for receiving payments",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="stripe_account_verified",
            field=models.BooleanField(
                default=False, help_text="Whether the Stripe account has been verified"
            ),
        ),
    ]
