# Generated by Django 4.2.23 on 2025-11-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_user_stripe_account_id_user_stripe_account_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="stripe_session_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe Checkout Session ID to prevent duplicate orders",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
