# Generated by Django 4.2.23 on 2025-11-27 21:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_add_stripe_session_to_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "platform_name",
                    models.CharField(
                        default="Marketplace Platform",
                        help_text="Name of the marketplace platform",
                        max_length=100,
                    ),
                ),
                (
                    "platform_stripe_account_id",
                    models.CharField(
                        blank=True,
                        help_text="Platform owner's Stripe Account ID for receiving commissions (starts with 'acct_')",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "commission_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=20.0,
                        help_text="Percentage of each sale that goes to platform (0-100)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MinValueValidator(100),
                        ],
                    ),
                ),
                (
                    "commission_enabled",
                    models.BooleanField(default=True, help_text="Enable/disable commission system"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
