# Generated by Django 4.2.23 on 2025-11-28 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_add_site_settings_commission"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="stripe_connect_status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("restricted", "Restricted"),
                ],
                default="not_started",
                help_text="Stripe Connect onboarding status",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="commission_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=20.0,
                help_text="Percentage of each sale that goes to platform (0-100)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
