# Generated by Django 4.2.23 on 2025-12-01 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_add_stripe_connect_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(
                db_index=True,
                help_text="Unique order number in format: ORD-YYYY-MM-NNNNNN",
                max_length=25,
                unique=True,
            ),
        ),
    ]
