# Generated by Django 4.2.19 on 2026-01-10 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.text import slugify


def generate_slugs_for_existing_categories(apps, schema_editor):
    """Generate unique slugs for existing categories"""
    Category = apps.get_model('accounts', 'Category')

    for category in Category.objects.all():
        if not category.slug:
            base_slug = slugify(category.name)
            slug = base_slug
            counter = 1

            # Ensure uniqueness
            while Category.objects.filter(slug=slug).exclude(pk=category.pk).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1

            category.slug = slug
            category.save(update_fields=['slug'])


def convert_existing_to_main_categories(apps, schema_editor):
    """Convert all existing categories to main categories"""
    Category = apps.get_model('accounts', 'Category')

    Category.objects.all().update(
        is_main_category=True,
        parent=None,
        is_approved=True,
        approval_status='approved'
    )


def create_general_category(apps, schema_editor):
    """Create the 'General' main category for miscellaneous items"""
    Category = apps.get_model('accounts', 'Category')
    User = apps.get_model('accounts', 'User')

    # Get first admin user or None
    admin_user = User.objects.filter(is_superuser=True).first()

    # Check if General category already exists
    if not Category.objects.filter(name__iexact='General').exists():
        Category.objects.create(
            name='General',
            slug='general',
            description='General category for items and services that do not fit into other categories',
            is_main_category=True,
            parent=None,
            created_by=admin_user,
            is_active=True,
            is_approved=True,
            approval_status='approved'
        )


def reverse_data_migration(apps, schema_editor):
    """Reverse migration - do nothing critical"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_update_order_number_format'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['parent__name', 'name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='approval_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending Review'), ('rejected', 'Rejected')], default='approved', help_text='Approval status of the category', max_length=20),
        ),
        migrations.AddField(
            model_name='category',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Whether category is approved for public use'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_main_category',
            field=models.BooleanField(db_index=True, default=False, help_text='Main categories can only be created by admins'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent category (null for main categories)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='accounts.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier', max_length=120),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, help_text='Category name', max_length=100),
        ),
        # Data migrations
        migrations.RunPython(
            generate_slugs_for_existing_categories,
            reverse_code=reverse_data_migration
        ),
        migrations.RunPython(
            convert_existing_to_main_categories,
            reverse_code=reverse_data_migration
        ),
        migrations.RunPython(
            create_general_category,
            reverse_code=reverse_data_migration
        ),
        # Now make slug field unique after all slugs have been generated
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier', max_length=120, unique=True),
        ),
        # Add constraints after data migration
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('parent', 'name')},
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'is_active'], name='cat_parent_active_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_main_category', 'is_active'], name='cat_main_active_idx'),
        ),
    ]
