# Generated by Django 4.2.19 on 2026-01-19 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_add_hierarchical_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Sender's full name", max_length=255)),
                ('email', models.EmailField(db_index=True, help_text="Sender's email address", max_length=254)),
                ('subject', models.CharField(help_text='Message subject', max_length=500)),
                ('message', models.TextField(help_text='Message content')),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('archived', 'Archived')], db_index=True, default='new', help_text='Message status', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text="Sender's IP address for spam prevention", null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/device information')),
                ('email_sent', models.BooleanField(default=False, help_text='Whether email notification was sent successfully')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes from admin')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who sent the message (if logged in)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='accounts_co_created_f7fa9a_idx'), models.Index(fields=['status', '-created_at'], name='accounts_co_status_c4096d_idx'), models.Index(fields=['email', '-created_at'], name='accounts_co_email_2f2d0a_idx')],
            },
        ),
    ]
